category:
 - Team Projects
 - "Libraries, Community Centers"
name: East Atlanta Library
stats:
 location: "Atlanta, Georgia"
 client: "Fulton County/City of Atlanta, Georgia"
 cost: "$3,200,000 US"
about: |
 East Atlanta Library is an 8,000 square foot,
 single story, neighborhood library and is
 Fulton County government’s first LEED
 Silver Certified building. The total budget
 for the project was $3.2 million. Along
 with typical library features, the library has
 expanded computer facilities, a community
 meeting room, and an exterior plaza where
 community events can be staged.
 
 The project was designed to take full
 advantage of natural light through the use of
 clerestories, sunshades and sun reflectors. A
 plenum HVAC system eliminates the need for
 ductwork and economically heats and cools
 the vaulted reading room.
 
 The building is steel frame construction, with
 brick veneer, a steel roof deck and a highly
 reflective PVC roof.
 
 ###Awards:
 East Atlanta Library was LEED Silver Certified
 by the United States Green Building Council
 in 2007.
 EAL was awarded “Best New Library for
 2005” by Atlanta Magazine